name: flutter_arch_manager

version: 1.0.0+1

publish_to: none

description: A new Flutter project.

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  get_cubit: ^1.1.0
  flutter:
    sdk: flutter
  cw_core:
    git:
      url: git@gitlab.com-codewave:codewave-technologies/codewave-flutter-core.git
      ref: main
  flutter_wiretap:
    git:
      url: git@gitlab.com-codewave:codewave-technologies/flutter-wiretap.git
      ref: main
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
