name: bg_removal_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  get_cubit: ^1.1.0
  path_provider: ^2.1.2
  flutter: 
    sdk: flutter
  cw_core: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/codewave-flutter-core.git
      ref: main
  flutter_wiretap: 
    git: 
      url: git@gitlab.com-codewave:codewave-technologies/flutter-wiretap.git
      ref: main
  camera: ^0.10.5+9
  image: ^4.1.7
  file_picker: ^8.0.0+1
  flutter_dropzone: ^4.0.0
  http: ^1.2.1
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
